// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEL6_iecHhiSbUCFuU9XKgCmP3aOZxcgs',
    appId: '1:838916082947:web:b17f9b85df7b8693ac2d36',
    messagingSenderId: '838916082947',
    projectId: 'whatsapp-backend-ceb46',
    authDomain: 'whatsapp-backend-ceb46.firebaseapp.com',
    storageBucket: 'whatsapp-backend-ceb46.appspot.com',
    measurementId: 'G-C5S50ZMTNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjQjvJ8b7QgcT45RFxIyERQiZrkrL-R2A',
    appId: '1:838916082947:android:06060680645de3a8ac2d36',
    messagingSenderId: '838916082947',
    projectId: 'whatsapp-backend-ceb46',
    storageBucket: 'whatsapp-backend-ceb46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRYDIKuFa_YGqskX3O6D0n19D7barMR0',
    appId: '1:838916082947:ios:c241603400c5d6eeac2d36',
    messagingSenderId: '838916082947',
    projectId: 'whatsapp-backend-ceb46',
    storageBucket: 'whatsapp-backend-ceb46.appspot.com',
    iosClientId: '838916082947-49hlqij9jirde13njrqmnc4l2f69uuch.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
